### ISSUE TITLE
ES 6 SyntaxError: Unexpected token =>

### ISSUE THREAD

**Issue by itree** [sectore/mithrilify#7]
when using with nodejs v 12 I get this error:

bundle.js:22
            ctrl.files().map(file => m.component(File, Object.assign({},  file
                                  ^^
## SyntaxError: Unexpected token =>

mithrilify seems to outputting ES6, is there way to have mithrilify output more compatible Javascript?

**Comment by sectore** [comment]
It seems that `browserify` (not `mithrilify`) bundles your code to ES6. `mithrilify` is just used for transformation. Please check the build setttings of your project.

**Comment by itree** [comment]
Ah thanks.  After checking I realize it has to do with MSX code: see below

```
    <form>
      {/* Bare component */}
      <Uploader/>
      {/* Component with attributes */}
      <Uploader onchange={ctrl.files}/>
      {/* Component with attributes and children */}
      <Uploader onchange={ctrl.files}>
        {ctrl.files().map(file => <File {...file}/>)}
      </Uploader>
      <button type="button" onclick={ctrl.save}>Upload</button>
    </form>
```

Is there away to write the MSX using ES5 for the files.map ?
